// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using zad2;

namespace zad2.Migrations
{
    [DbContext(typeof(WeatherByCity))]
    partial class WeatherByCityModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("zad2.DownloadWeather", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("dt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("timezone")
                        .HasColumnType("INTEGER");

                    b.Property<float>("visibility")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("DownloadWeathers");
                });
#pragma warning restore 612, 618
        }
    }
}
